### ISSUE TITLE
Local Encryption

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#11]
@ctsims @millerdev Is local encryption supported by CommCare?

**Comment by ctsims** [comment]
Martijn,

On CommCare Android all user data is encrypted at rest through AES256-bit
encryption with Keys generated off device and exchanged securely (since the
local source of randomness on j2me is not super trustworthy).

On CommCare J2ME there is a mechanism to enable encryption but it is not
turned on by default due to issues with the storage layer on j2me.

-Clayton

**Comment by MartijnR** [comment]
Thanks  Clayton,

So this does not sound like it is part of the XForm format then (unlike in ODK where the public key is stored in the form itself). Please reopen if I misunderstood.
