### ISSUE TITLE
Bind type "intent"

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#21]
Can this bind type be anything? String as well as binary?

**Comment by ctsims** [comment]
We expect the return from this to be a string. Binary returns are supported only through the other attributes. So you'd set up a binary question and manually bind it to one of the return intent keys, since the incoming question's type is set to "intent".

We require the type to be explicitly "Binary" for any binary returns

**Comment by MartijnR** [comment]
I'll leave this open. I have the feeling it might become clear when the other intent issues are clarified. Otherwise an XForm snippet would help me.

**Comment by ctsims** [comment]
We just leave this as basically uncast string data. I don't believe we
allow attachment style binary (only base64 style inline binary)

-Clayton
