### ISSUE TITLE
repeat control children

### ISSUE THREAD

**Issue by MartijnR** [dimagi/xform-spec#25]
You mentioned:

> Note: All children of a repeat control must be children of the repeat nodeset 

Is this special? Shouldn't any form control, group, repeat element be a child of its parent if the parent has a ref or nodeset attribute?

**Comment by ctsims** [comment]
Hey,

So that would be intuitive, wouldn't it! The XForms specification actually doesn't require any specific parity between the parentage of a <group> control. Only <repeats> have this restriction according to the W3C spec.

it's actually fairly helpful sometimes in allowing you to build constructs which rely on the form structure, but it's generally a bad idea.
